AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: libvips-sharp-jp2
      ContentUri: dist/sharp-lambda-layer.zip
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - nodejs14.x
        - nodejs16.x
        - nodejs18.x
      LicenseInfo: Apache-2.0
  LayerPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties: 
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref SharedLayer
      Principal: "*"
Outputs:
  LayerArn:
    Value: !Ref SharedLayer
